### ISSUE TITLE
fetlife has stopped

### ISSUE THREAD

**Issue by Cayce7** [fetlife/fetlife-android#31] opened 2016-05-11 00:37 UTC
I just downloaded the app last night for the first time and I'm getting the "unfortunately fetlife had stopped" error.

**Comment by kistitan** [comment] 2016-05-11 17:48
Hi Cayce,

Thanks very much for reporting the issue.
I will take a look at it asap.

San you please uninstall and reinstall the app and check if you get the same result?

(Sorry for asking you for this annoying step that might not be able to help and even if it helps the issue still should be solved on our side, but even this tiny information, if reinstall makes and different could help us to track down the issue).

Thanks a lot for your help and patience

**Comment by Bryan76** [comment] 2016-05-11 17:54
I didn't have the app previously installed.

But to test, I just uninstalled and re-installed.

- Crash on installation.
- Then login screen showed up
- Logged in with user & pass
- Crash
- Everytime I run it... Crash

Verizon Nexus 6P
Android 6.0.1
Android Security Patch Level April 2, 2016

**Comment by kistitan** [comment] 2016-05-11 17:56
Perfect, thanks a lot for your help.
Sorry for asking you for this but even excluding this possibility help us a lot to track down the issue.
I will take a look at it asap.

Thanks again for your help and patience

**Comment by Bryan76** [comment] 2016-05-11 17:57
Not at all, I know how these thins go.  If you need any other info or tests, let me know.

**Comment by restrainedimages** [comment] 2016-05-11 19:43
Looks like same as #30.
Interestingly it is also a Nexus (6P vs my 6) running the latest version of Android. That is starting to look like the common element.

**Comment by kistitan** [comment] 2016-05-11 20:24
Yep, true.
I am testing right now with an old Nexus 5 but latest os and no issue.
In the given release there were only some bug fixes and one build tool change.
I will try to revert the change with the build tool and see how it goes (it is suspicious because the crash during install).

If it won't help I will make a special build for you guys so I can log more information about the crash and see what exactly goes wrong...

**Comment by GojuSuzi** [comment] 2016-05-11 23:01
Just wanted to add to this:
Also Nexus 6, running 6.0.1 (1/May/2016 security patch), and getting this "Fetlife has stopped" crash. It didn't crash on install here, that went fine, but on opening the app, it hangs on the black screen for quite a while, about 20-30 seconds, gave the error and then opened the login page anyway, seemed to work and then crash whilst still displaying log in screen; after this, black screen and crash on load every time.
Uninstall/reinstall just repeats the same scenario.
Clearing data/cache repeats, too, including the initial 'fake crash'.
Phone was actually a RMA replacement I picked up yesterday so as close to clean as you'll get, definitely no old version.

I've also tried it on my old Nexus 4, running 5.1, and that behaved exactly the same; got past the lazy and updated to 5.1.1 and same deal. So it doesn't seem strictly limited to Nexus 6 and/or Marshmallow, but a fairly specific set of complainants so far.

**Comment by Bryan76** [comment] 2016-05-11 23:19
More than willing to run a custom build to get more info.  And I also agree, as I would consider this very "in development" and probably not even alpha yet, speed of development over installation ease for now.

**Comment by Crinkle62** [comment] 2016-05-12 02:47
I have a Galaxy s7 &  the app has been crashing directly after opening. I have had the app installed for several days.

**Comment by justrob1980** [comment] 2016-05-12 02:59
I am having the same problem on my Samsung Galaxy Note 5 (SM-N920V) running Android 6.0.1 Security Patch: April 2, 2016 - I've uninstalled and reinstalled several times. Application crashes upon launch with "Unfortunately, FetLife has stopped" error message.

**Comment by jaseiffert** [comment] 2016-05-12 03:13
Having same problem but didn't crash on install. 
Samsung Galaxy S5 Android 5.1.1

I did get to a login screen after first crash but crashes every time after that. 

Uninstall and reinstall a fresh download from git today.

**Comment by chaos2entropy** [comment] 2016-05-12 03:55
Same error message/crash.
Note 4, system 5.1.1

**Comment by chaos2entropy** [comment] 2016-05-12 03:57
Still crashing after reboot and reinstall on my Note 4.

**Comment by impchild** [comment] 2016-05-12 07:36
Crash on install. Crash after log in. Crash every time after that i have tried. LG G3 and likely not newest anything as it is An older phone.

**Comment by LowRentTechGuy** [comment] 2016-05-12 16:47
Same issue
Crash on installation.
Then login screen showed up
Logged in with user & pass
Crash
Everytime I run it... Crash

Samsung Note 5
Android: 6.0.1
Patch level: April 2nd 2016

**Comment by kistitan** [comment] 2016-05-14 21:23
Hi all,

First of all thank you very much for your patience and support.
I uploaded with a new app version.
Aside some adding some new features I also reverted some that was added in the previous version (son in theory could cause the problem).
This can help, but it's not for sure :(

However I have another idea, that could cause the issue.
When you uninstall the application android OS not always clear all data. It is something I cannot influence from the application. What we usually is that after installation we clear everything to make sure there is no incomapatible data.
However I use for the app an external library that might not do it properly.

So what I would like to ask you guys is to install the app (any version) for to the app setting on your phone, find the app and go the data storage section and there clear all data.
After that uninstall the app, and reinstall the latest version.

Please let me know if this process change anything.

Thanks you again very much.

**Comment by Crinkle62** [comment] 2016-05-14 23:09
Still no working. It will be awhile, but you will figure it out.

**Comment by kistitan** [comment] 2016-05-15 00:59
Hmm... it was confirmed it works for some now.
So there might be separate issues.
I will do the special logging build for those it still does not work.
Thanks for the trust :)

**Comment by restrainedimages** [comment] 2016-05-15 09:06
Just an update - I...
Started with the previous version installed.
Cleared the application data & cache.
Uninstalled.
Installed the new version.
Launched.

I get different results to previously...
No pause.
Immediate crash.
No login screen.

**Comment by GojuSuzi** [comment] 2016-05-15 13:14
Working here now. To confirm though, I cleared data on the glitches one before uninstall, and after insralling the new version got the "Fetlife has stopped" again without the log in screen, but after clearing data on the new one it worked. So you're spot on with the 'not really clearing' thing.

**Comment by kistitan** [comment] 2016-05-15 13:29
Ok guys, thanks for everyone for positive attitude.
I am very puzzled as I have 3 test phones and on all of them works perfectly, also a few friends testing without issues.

But if course we are going to make it work for you too.
Today I am going to release a new version that will fail too but we can see the crash log why.

Thanks again for the patience, I get back to you soon.

**Comment by restrainedimages** [comment] 2016-05-15 13:38
Another update...
This time I started with the latest version installed.
I cleared the data / cache.
Now it prompts for the username/password and once entered works as expected.
No crash!!!

My steps are now effectively the same as GojuSuzi. I just did it in two parts. (Thanks! That last post prompted me to test a new scenario that solved it for me.)

So my recommended steps for anyone who still has the problem...
1) Clear data.
2) Uninstall.
3) Install the latest version.
4) Run
5) If is crashes then clear the data again and try again.

I think it is step 5 (clearing the data with the latest version installed) that is fixing the issue.

**Comment by kistitan** [comment] 2016-05-15 13:45
Thank you very much for test!
It is very useful information!

The external library I use for storing data in database is very useful, but it seems I need to add additional checks for clearing invalid data when needed.

In next version aside catching and reporting error I will add some additional explicit checks for this, so you won't need to uninstall / reinstall the new versions anymore.

I keep you updated

**Comment by Bryan76** [comment] 2016-05-16 02:56
1) Clear Data
2) Uninstall
3) Install latest version
4) Run (Crashes)
5) Clear Data (Android Settings -> Apps -> FetLife -> Clear data)

Step 5 seems to have done it.  I can now run the app.

**Comment by justrob1980** [comment] 2016-05-16 13:14
@Bryan76's methodology worked for me with the newest build but the app appears to be just the email interface ... is that the case?

**Comment by Crinkle62** [comment] 2016-05-16 17:31
That's all I got. The email interface. It stop crashing.

**Comment by thezerogod** [comment] 2016-05-16 17:35
The present functionality is email only as stated in the original app
announcement thread. The dev team is looking to expand that in the future.

FYI I'm on a Nexus 6 running Marshmallow and had the same issues; the clear
data/uninstall/crash/clear data path worked for me as well.

**Comment by kistitan** [comment] 2016-05-16 22:05
Indeed the current version contains only usage of conversation API, so currently you can use the FetLife app for chatting and to continue your already existing conversation.
We are going to extend the functionality step by step until we get the to full FetLife Android app.

The next 2 upcoming feature is downloading user profile images for conversations and starting new conversation.

About the crash.
I have just added a new version (0.5.1).
This version contains an automatic database clean in case of finding some incompatible data from the previous version. So hopefully this issue won't occur anymore.
I also added a logging functionality so in case of a crash a fetlife.log file will be generated on your external directory. Please provide us this file in case of any crash you face.

From now on aside the latest release you will also access some recent version.
So in case of any showstopper issue with the latest version you can still fallback to the previous one.

Please let me know if you have crash issues with the latest version too, otherwise I am going to close this thread and continue with feature development.
Thanks you for all your help!

**Comment by Bryan76** [comment] 2016-05-17 02:40
Looks great.

App now refuses to install if it's already installed.  Clearly part of the "Faster development/more awkward install" methodology, which I approve.

Crashes on install, login, and use are gone for me.

**Comment by kistitan** [comment] 2016-05-19 03:10
Thanks you for your understanding, however from version 0.51 onwards you won't need any re/uninstall process, you can simply install the new version and everything should work :)
In theory of course... ;)

New version with profile images is coming soon...

I close this thread now as it seems crash at start is gone

Thank you all

**Comment by LeBlondTenebreux** [comment] 2016-05-24 08:43
Hello, I'm really sorry but I think there's still a bug.
I just downloaded the last version (0.51), and had a direct crash at startup (no login window, just the crash message). I could not find any fetlife.log anywhere (I activated debugging on FetLife application in the dev parameters on my phone, with no success).

I'm on Android 4.1.1 on an Asus Padfone 1 (A66) (french locales). It crashes both in phone and in tablet mode.
If you need any more details, please ask.

Regards

**Comment by LeBlondTenebreux** [comment] 2016-05-31 07:40
Version 0.60 definitively corrected the issue, thanks :)

**Comment by Daddy** [comment] 2016-06-01 22:07
@kistitan v0.8 (current version on repository) re-introduces this bug and currently crashes upon every attempt to launch the app on my Nexus 6P on Android 6.0.1. The same issue is effecting my other device which is a Note 5 (Samsung) on Android 5.X.

**Comment by kistitan** [comment] 2016-06-02 09:28
Hi Daddy,

Thanks for letting me know.
I have hard time with the db library I use.
It is very convenient, but clearing db gives some trouble on some devices

There is a new major release of the library, so let's hope it solved that issue.
I will integrate it together with the crash analytics library so I will see exactly where things go wrong.

Our first milestone with version 1.0 is coming but this issue should be definitely solved before.
Thanks again for reporting.

**Comment by Daddy** [comment] 2016-06-02 19:15
@kistitan Thank you for continuing to investigate it. I'm not sure how Android app installations are handled but if you're able to run any functions prior to the install (unless it's just strictly copying the .apk files over) you could try forcing a logout to clear the database once #50 is resolved. You should change the milestone to "Android App v1.0" to match the tags @JohnBaku added. 👍

**Comment by kistitan** [comment] 2016-06-03 07:35
installation process is out of the app's influence zone.
There are workarounds but we don't want those for sure ;)

Currently it works like the way that database version is stored and if it increased the whole database is dropped and recreated.

The funny thing is that this works perfectly on my personal device and I have no clue why it doesn't work on yours 

I found some threads about bugsin the db library that might be related. Those are fixed in the new version so update can help.

in the meanwhile can you please check if you have a FetLife.log file in your root folder? sdcard or internal (depends on the device)

Thank you

**Comment by Daddy** [comment] 2016-06-03 07:55
@kistitan Here you go!
As a reminder, this while trying to upgrade from 0.6.1 to 0.8 (if that helps).

> 2016.06.01.12.55.52
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bitlove.fetlife/com.bitlove.fetlife.view.ConversationsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at com.bitlove.fetlife.model.resource.ImageLoader.loadImage(ImageLoader.java:70)
	at com.bitlove.fetlife.view.ResourceActivity.onCreate(ResourceActivity.java:98)
	at com.bitlove.fetlife.view.ConversationsActivity.onCreate(ConversationsActivity.java:48)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more

**Comment by Bryan76** [comment] 2016-06-03 15:34
Confirmed, same issue when upgrading to 0.8 on a Verizon Nexus 6P. Clearing the data fixed the issue. :)

**Comment by kistitan** [comment] 2016-06-03 17:36
Hi guys,

Actually it is a different issue, but same effect.
Thanks for reporting the stack trace it helped a lot!!

From the next version you won't have to report stacktraces an more as crashes will be automatically reported, so instead of a simple crash I will see more about why and how did it happen.

This bug is resolved now and bug fix will be part of the next release.

Thanks again

**Comment by Bryan76** [comment] 2016-06-03 17:46
Awesome... keep up the great work!  I'm really excited about this project.

**Comment by kistitan** [comment] 2016-06-04 08:04
Fixed in version 0.8.5

**Closed by kistitan** 2016-06-04 08:04 UTC
Labels: bug
