### ISSUE TITLE
Semicolons mess up messages ; - RESOLVED

### ISSUE THREAD

**Issue by kdom13** [fetlife/fetlife-android#88] opened 2016-06-20 00:20 UTC
When using a semicolon, as in a winky face ;) it would mess up the messages.  After updating to 1.0.2 though, I'm noticing that this is fixed.  Just figured I'd post anyways.

**Comment by reneklacan** [comment] 2016-06-20 14:38
Thank you for reporting this issue!

This was probably caused by the way we encoded message in previous releases. I think it's related to the problems we had with passwords containing special characters. As it's solved I think we can close this issue. What say you @kistitan ?

**Comment by kdom13** [comment] 2016-06-21 07:51
If it was used in the middle of the message, anything including and after the semicolon would get cut off.  If used in the beginning of the message, the message would fail to send.  Again, it seems corrected in 1.0.2 (I sent a few messages) but I figured I'd make note of it since nobody else has.

**Comment by kistitan** [comment] 2016-06-21 17:11
Indeed issue has been fixed in 1.0.0. 
All api called failed with special characters,
I had an issue for it but already closed.

But thanks for reporting it is better to have it more than once than not at all.

**Closed by kistitan** 2016-06-21 17:11 UTC
